//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programmersdigest.MT940Parser.Parsing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BalanceParserResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BalanceParserResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("programmersdigest.MT940Parser.Parsing.BalanceParserResx", typeof(BalanceParserResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit/Credit Mark must be &apos;C&apos; or &apos;D&apos;. Actual:.
        /// </summary>
        internal static string dc {
            get {
                return ResourceManager.GetString("dc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The balance data ended unexpectedly. Expected value Amount with a length of at least 1 decimal..
        /// </summary>
        internal static string endUnexpectedlyAmount {
            get {
                return ResourceManager.GetString("endUnexpectedlyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The balance data ended unexpectedly. Expected value Currency with three uppercase letters..
        /// </summary>
        internal static string endUnexpectedlyCCY {
            get {
                return ResourceManager.GetString("endUnexpectedlyCCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The balance data ended unexpectedly. Expected credit debit field..
        /// </summary>
        internal static string endUnexpectedlycrdb {
            get {
                return ResourceManager.GetString("endUnexpectedlycrdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The balance data ended unexpectedly. Expected value Date with a length of six characters..
        /// </summary>
        internal static string endUnexpectedlyDate {
            get {
                return ResourceManager.GetString("endUnexpectedlyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert value to Decimal:.
        /// </summary>
        internal static string noDecimal {
            get {
                return ResourceManager.GetString("noDecimal", resourceCulture);
            }
        }
    }
}
